---
# handlers file for common
- name: Restart firewalld
  service: name=firewalld state=restarted
  become: true
- name: Reload systemctl
  command: systemctl daemon-reload
  become: true
- name: Restart Artifactory
  service: name=artifactory state=restarted
  become: true
...
