---
- name: "Check OS version for Flannel"
  set_fact:
    install_old_flannel: "((ansible_distribution == 'CentOS' or ansible_os_family == 'RedHat') and ansible_distribution_major_version == '7') | bool"

- name: "Install Flannel Virtual Network for pod communication (old)"
  shell: |
    kubectl -n kube-system get deployment coredns -o yaml | sed 's/allowPrivilegeEscalation: false/allowPrivilegeEscalation: true/g' | kubectl apply -f -
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/{{ coreos_flannel_sha_commit }}/Documentation/kube-flannel.yml
  when: "install_old_flannel | bool"

- name: "Install flannel as a pod network"
  shell: |
    kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
  when: "not install_old_flannel | bool"
...
