---
# - name: "Generate Calico manifest file"
#   template:
#     src: "cni/calico/kube-calico.yaml.j2"
#     dest: "/tmp/kube-calico.yaml"
#   become: true

- name: "Download Calico manifests"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/{{ item }}"
    dest: "/tmp/{{ item }}"
  loop:
    - tigera-operator.yaml
    - custom-resources.yaml

- name: "Fix Calico manifests' CIDR"
  ansible.builtin.replace:
    path: /tmp/custom-resources.yaml
    regexp: 'cidr: 192.168.0.0/16'
    replace: 'cidr: {{ pod_subnet }}'

# - name: "Apply Calico manifest"
#   ansible.builtin.shell: |
#     kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/tigera-operator.yaml
#     kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/custom-resources.yaml

- name: Pause for 5 seconds before creating Tigera Operator
  ansible.builtin.pause:
    seconds: 5

- name: "Create tigera operator"
  ansible.builtin.shell: kubectl create -f /tmp/tigera-operator.yaml

- name: Pause for 5 seconds before creating Calico Custom Resources
  ansible.builtin.pause:
    seconds: 10

- name: "Create Calico custom resources"
  ansible.builtin.shell: kubectl create -f /tmp/custom-resources.yaml

- name: "Wait for Calico to be up and running"
  ansible.builtin.shell: watch kubectl get pods -n calico-system

...
