---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- name: Install Python modules for Ansible
  raw: "{{yum_python_install_raw}}"
  args:
    warn: false # set warn=false to prevent warning
  become: true
- name: Install Python modules for Ansible
  shell: "{{yum_install_command}}"
  args:
    warn: false # set warn=false to prevent warning
  become: true
#- name: debug, please remove
#  debug:
#    msg: "{{ansible_distribution_major_version}}, {{ansible_distribution_file_variety}}"
#- include: rhel_8.yml
#  when: ansible_distribution_major_version == '8' and ansible_distribution_file_variety == 'RedHat'
#- include: default.yml
#  when: ansible_distribution_major_version != '8' or ansible_distribution_file_variety != "RedHat"
...
