---
# tasks file for buildah
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- name: Install Epel repository
  package:
    name: "{{epel_repo}}"
    state: present
  when: epel_repo is defined
  become: true
- name: Install required packages
  package:
    name: "{{required_packages}}"
    state: present
  become: true
- name: Install Buildah packages
  package:
    name: "{{buildah_packages}}"
    state: present
  become: true
#- name: Install Cockpit Buildah packages
#  package:
#    name: "{{cockpit_packages}}"
#    state: present
#  become: true
#- name: Install Buildah PIP modules
#  pip:
#    name: "{{pip_packages}}"
#  become: true
#- name: Open buildah ports
#  firewalld:
#    port: "{{item}}"
#    permanent: yes
#    state: enabled
#  with_items:
#    - "{{buildah_ports}}"
#  when: buildah_ports is defined
#  notify: Restart firewalld
#  become: true
#- include: buildah_users.yml
...
