---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: "Validate state"
  assert:
    that: state == "absent" or state == "present"
    fail_msg: "state must be either absent or present"

- include_tasks: remove.yml
  when: state == "absent"

- name: Populate service facts
  ansible.builtin.service_facts:
  when: state == "present"

- include_tasks: install.yml
  when: (state == "present") and not ('containerd.service' in ansible_facts.services )
...
