---
# tasks file for common
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- assert:
    that: "state == 'present' or state == 'absent'"

- include_tasks: install.yml
  when: "state == 'present'"

- include_tasks: remove.yml
  when: "state == 'absent'"
...
