---
# handlers file for common
- name: restart ntp
  service:
    name: "{{ ntp_daemon }}"
    state: restarted
  when: ntp_enabled
  become: true

- name: restart chronyd
  service:
    name: "{{ ntp_daemon }}"
    state: restarted
  when: ntp_enabled
  become: true
...
...
