---
- name: "Install cri-o"
  package:
    name: "cri-o"
    state: absent
  become: true

- name: Copy containerd containerd.conf file
  shell: "dnf module disable cri-o:{{ crio_version }}"
  become: true

- name: "Remove configuration files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/modules-load.d/crio.conf
    - /etc/sysctl.d/99-kubernetes-cri.conf
  become: true
...
