---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_os_family }}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: "Add docker repository CentOS/RedHat 8/Fedora"
  shell: "{{ add_docker_repo_command }}"
  become: true
  when: "((ansible_distribution == 'CentOS' or ansible_os_family == 'RedHat') and ansible_distribution_major_version == '8' ) or ansible_distribution == 'Fedora'"

- name: "Add docker repository CentOS/RedHat 7"
  yum_repository:
    name: docker-ce
    description: Docker
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: 1
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
  become: true
  when: "(ansible_distribution == 'CentOS' or ansible_os_family == 'RedHat') and ansible_distribution_major_version == '7'"

...
