---
# tasks file for cockpit
- name: Load vars file for the host {{ansible_architecture}}/{{ansible_distribution}}/{{ansible_distribution_major_version}}.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_architecture}}.yml"
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- name: Install Cockpit packages
  package: name={{cockpit_packages}} state=present
  become: true
#  with_items:
#    - "{{cockpit_packages}}"
#- name: firewalld - Open Cockpit ports
#  firewalld:
#    service: cockpit
#    permanent: yes
#    state: enabled
#  become: true
#  notify: Restart firewalld
- name: Execute firewall role
  include_role:
    name: 'sec/firewalld'
  vars:
    firewall_services: cockpit
- name: Enable Cockpit service
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes
  become: true
- name: Start Cockpit
  service:
    name: cockpit
    state: started
  become: true
...
