---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- name: Install PostgreSql python libraries
  package:
    name: "{{pgsql_python_libraries}}"
    state: present
  become: true
- name: Open pgSql firewall ports
  include_role:
    name: 'core/firewall'
#  vars:
#    firewall_services: "{{firewall_services}}"
- name: Check if PostgreSql service exists
  stat: 'path=/etc/systemd/system/multi-user.target.wants/postgresql.service'
  register: pgsql_service_status
#- name: Show PostgreSQL service status
#  debug:
#    msg: '{{ pgsql_service_status }} exists!'
#  when: pgsql_service_status.stat.exists
#- name: Show PostgreSQL service status
#  debug:
#    msg: '{{ pgsql_service_status }} does not exist.'
#  when: not pgsql_service_status.stat.exists
- include: pgsql.yml
  when: pgsql_version is not defined
  #when: not pgsql_service_status.stat.exists and pgsql_version is not defined
- include: pgsql_version.yml
  when: pgsql_version is defined
  #when: not pgsql_service_status.stat.exists and pgsql_version is defined
#- include: pgsql_config.yml
#  when: not pgsql_service_status.stat.exists
...
