---
# tasks file for cockpit
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- name: Install Postfix packages
  package: name={{item}} state=present
  become: true
  with_items:
    - "{{postfix_packages}}"
- name: Enable and start Postfix service
  systemd:
    name: postfix
    state: started
    enabled: yes
...
