---
- name: "Download kind"
  ansible.builtin.get_url:
    url: "https://kind.sigs.k8s.io/dl/v{{ kind_version }}/kind-linux-amd64"
    dest: "/usr/local/bin/kind"
    mode: "0755"
  become: true

- name: "Download kubectl"
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{ k8s_version }}/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: "0755"
  become: true


- name: "Set kind executable permission"
  ansible.builtin.file:
    path: "/usr/local/bin/kind"
    mode: "0755"
  become: true

- name: "Execute docker installation role"
  include_role:
    name: '{{ container_role_folder }}/docker'
  vars:
    state: present
  when: "cri == 'docker'"

- name: "Execute podman installation role"
  include_role:
    name: '{{ container_role_folder }}/podman'
  vars:
    state: present
  when: "cri == 'podman'"
...
