---
# handlers file for common
- name: Restart firewalld
  service: name=firewalld state=restarted
  become: true
- name: Reload firewalld
  command: firewall-cmd --reload
  become: true
- name: Restart SonarQube
  service: name=sonar state=restarted
  become: true
...
