---
- name: Drop cloud calls
  shell: "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT_direct 10 -p udp --dport 53 -m string --algo bm --hex-string '|03|cloud|00|' -j DROP"
  become: true
  notify: Restart firewalld
...
