---
# handlers file for common
- name: Restart firewalld
  service: name=firewalld state=restarted
  become: true
#- name: Reload systemctl
#  command: systemctl daemon-reload
#  become: true
- name: Restart Foreman Proxy
  service: name=foreman-proxy state=restarted
  listen: 
    - Restart xinetd
    - Restart dhcpd
  become: true
- name: Restart xinetd
  service: name=xinetd state=restarted
  become: true
- name: Restart dhcpd
  service: name=dhcpd state=restarted
  become: true
...
