---
# tasks file for iptables
- name: Include vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- name: Template close script
  template:
    src: "fclo01.sh.j2"
    dest: "{{script_bin_folder}}/fclo01.sh"
    mode: 0755
  become: true
- name: Template open script
  template:
    src: "fope01.sh.j2"
    dest: "{{script_bin_folder}}/fope01.sh"
    mode: 0755
  become: true
- name: Template iptables configuration service
  template:
    src: "iptables_configure.service.j2"
    dest: "/etc/systemd/system/iptables_configure.service"
    mode: 0644
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true
#- name: Enable and start iptables_configure service
#  systemd:
#    name: "iptables_configure"
#    enabled: yes
#    state: started
#  become: true
...
