---
# tasks file for cockpit
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- name: Install Apache Http packages
  package:
    name: "{{httpd_packages}}"
    state: present
  become: true
#- name: firewalld - Open Apache Http ports
#  firewalld:
#    service: "{{firewall_services}}"
#    permanent: yes
#    state: enabled
#  become: true
#  notify: Restart firewalld
- name: Enable Httpd service
  systemd:
    name: httpd
    state: started
    enabled: yes
  become: true
- name: Start Apache Http
  service:
    name: httpd
    state: started
  become: true
- name: Execute firewall role
  include_role:
    name: 'core/firewalld'
# SSL
# yum install openssl  mod_ssl
# firewall-cmd --add-service https --permanent
...
