---
# tasks file for cockpit
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- name: Start Apache Http
  service:
    name: httpd
    state: restarted
  become: true
...
